name: build
on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - 'Containerfile'
      - 'documentation/**'
      - 'temp/**'
      - '.gitignore'

  pull_request:
    branches:
      - main
    types: # don't run build for Draft PRs
      - opened
      - reopened
      - synchronize
      - ready_for_review
    paths-ignore:
      - 'README.md'
      - 'Containerfile'
      - 'documentation/**'
      - 'temp/**'
      - '.gitignore'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      DEBUG: 'true'
      DEBIAN_FRONTEND: noninteractive
      NETCDF_RELEASE: https://api.github.com/repos/Unidata/netcdf-fortran/releases/latest
    steps:
      - uses: actions/checkout@v4
      - name: Install libnetcdf
        run: |
          apt update -y && apt install -y --no-install-recommends \
            hdf5-tools hdf5-helpers libhdf5-dev libhdf5-serial-dev libnetcdf-dev
      - name: Install gfortran and mpifort
        run: apt install -y --no-install-recommends make mpich gfortran
      - name: Install netcdf4-fortran
        run: |
          export NETCDF_URL=$(curl $NETCDF_RELEASE | jq -r '.tarball_url') && \
          curl -L "$NETCDF_URL" --output netcdf.tar.gz && \
          tar -xzf netcdf.tar.gz && \
          cd Unidata-netcdf* && \
          ./configure && make && make install && ldconfig && \
          nf-config --all
      - name: Build
        run: NETCDF4_LIB=$(nc-config --flibs) NETCDF4_INCLUDE=$(nc-config --fflags) make
